### ISSUE TITLE
Deprecated mapbox API

### ISSUE THREAD

**Issue by martinosk** [dfds-frontend/ships-on-map#9]
The API being used to get map tiles is deprecated by mapbox. We should change to https://docs.mapbox.com/api/maps/#static-images as the current API could stop working any time.

**Comment by kunukn** [comment]
The map is no longer shown on https://ships-on-map.tech 

I have a PR that fixes that. 

Here is a demo where the map works.
https://ships-on-map.kunukn.vercel.app/ 

When it get fixed. Then the https://ships-on-map.tech can be updated by running this in the command line.

```bash
vercel --prod
```
